### ISSUE TITLE
Send UNIX timestamp over CAN

### ISSUE THREAD

**Issue by Bonnee** [eagletrt/telemetria-sender#10]
Telemetry needs to send the UNIX timestamp with [this CAN message](https://github.com/eagletrt/can-cicd/blob/ea662d6e264cdd68ac856359e6726d26c773ac06/networks/Primary/network.json#L36) after having acquired correct time through GPS. Ideally, this message should be repeated every ~30sec-1min to keep every device synchronized.

**Comment by euberdeveloper** [comment]
If the GPS is not plugged or it is, for instance, inside the lab (where there is no field), the GPS logs an unpredictable number as timestamp. When there is no field I do not know how to solve it, but if the GPS is not plugged and the telemetry has a SIM, the timestamp is in any case correct because of the net. Hence, should I use the normal timestamp (from the net) and fallback to the GPS only if there is no SIM (and do nothing if both the SIM and the GPS are unplugged)?

**Comment by Bonnee** [comment]
Maybe, with some NTP server configuration we can fuse the two time sources together to get a more accurate and reliable timestamp, But for the time being I am ok with doing what you suggested.
